### ISSUE TITLE
improper setup leads to successful deployment

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#120]
I didn't setup rsa private keys but ran skaffold run successfully.

All pods are healthy but the frontend is not responding on its IP.

Logs show an exception, so I'm guessing a health probe that should be able to
catch this class of issues if homepage is not loading.

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-15 14:42:27 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Comment by Daniel-Sanche** [comment]
Hmm interesting, I get stuck on ContainerCreating when I don't have the secret added:
```
Warning  FailedMount       31s (x3 over 5m)      kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[publickey], unattached volumes=[publickey default-token-7r568]: timed out waiting for the condition
```

**Comment by ahmetb** [comment]
I think it works because the secret is also in extras/jwt/* –and gets overwritten. See #125.

**Comment by Daniel-Sanche** [comment]
So it sounds like it's not a secrets issue then? It looks like the loadgenerator might be sending invalid data for some reason. Is this over knative?

**Comment by ahmetb** [comment]
Yeah I'm not sure. This is not knative. Encountered via `skaffold run` on master.

**Comment by Daniel-Sanche** [comment]
Closing this in favour of https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/122, which seems to show the same error
