### ISSUE TITLE
frontend receiving 404s from userservice

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/bank-of-anthos#122]
I think I've set up correctly with 85a8638 using skaffold. Frontend shows
error:

```text
[2020-04-15 15:07:36 +0000] [6] [INFO] Starting gunicorn 20.0.4
[2020-04-15 15:07:36 +0000] [6] [INFO] Listening at: http://0.0.0.0:8080 (6)
[2020-04-15 15:07:36 +0000] [6] [INFO] Using worker: threads
[2020-04-15 15:07:36 +0000] [9] [INFO] Booting worker with pid: 9
[2020-04-15 15:07:52 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-15 15:07:56 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:07:58 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:08:00 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=dfb8f3be-a1fb-4ff1-a48f-07dafa24a345&password=password
[2020-04-15 15:08:02 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=dfb8f3be-a1fb-4ff1-a48f-07dafa24a345&password=password
[2020-04-15 15:08:04 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=dfb8f3be-a1fb-4ff1-a48f-07dafa24a345&password=password
[2020-04-15 15:08:11 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=dfb8f3be-a1fb-4ff1-a48f-07dafa24a345&password=password
[2020-04-15 15:08:11 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:08:13 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/2544223503 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20ecc29350>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/2544223503 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20deead090>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/8338298020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee9c6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/8338298020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee5c410>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20deead350>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20ecc29410>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:20 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/1523820362 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee8ff10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:20 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/1523820362 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee9c4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:21 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/2544223503 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee66a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:21 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/2544223503 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee9dad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:21 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/8338298020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20ee478f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:21 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/8338298020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20deead490>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:22 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/1523820362 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20ee492a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:22 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee5aa10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:23 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/8338298020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee9dd10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:24 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/8338298020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee9c750>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:25 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/2544223503 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20ecc49510>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:25 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/3646654731 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee66d50>, 'Connection to transactionhistory timed out. (connect timeout=3)'))
[2020-04-15 15:08:25 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/1523820362 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20ee4923d0>, 'Connection to transactionhistory timed out. (connect timeout=3)'))
[2020-04-15 15:08:27 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee74110>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:28 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/2544223503 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20deead650>, 'Connection to transactionhistory timed out. (connect timeout=3)'))
[2020-04-15 15:08:28 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:08:28 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/6907390275 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20ecc5e750>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:28 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee74e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:29 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/8338298020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee5c810>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:30 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/8338298020 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee5c610>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:31 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20deeadc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:31 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/1523820362 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee8fc10>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:31 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/6907390275 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee9c790>, 'Connection to transactionhistory timed out. (connect timeout=3)'))
[2020-04-15 15:08:32 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee9cd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:32 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/2544223503 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee7c890>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:33 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/2544223503 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee66e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:34 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/1523820362 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee5a390>, 'Connection to transactionhistory timed out. (connect timeout=3)'))
[2020-04-15 15:08:34 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/3646654731 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee78c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:34 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/8338298020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20ee492e90>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:35 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/6907390275 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee81290>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:37 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/3646654731 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dfdccf10>, 'Connection to transactionhistory timed out. (connect timeout=3)'))
[2020-04-15 15:08:37 +0000] [9] [ERROR] HTTPConnectionPool(host='transactionhistory', port=8080): Max retries exceeded with url: /transactions/8338298020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20deead750>, 'Connection to transactionhistory timed out. (connect timeout=3)'))
[2020-04-15 15:08:37 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/2544223503 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20deeadc50>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:38 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/1523820362 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20ecc49b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:39 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/6907390275 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20dee5c5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2020-04-15 15:08:41 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/3646654731 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee66ed0>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:41 +0000] [9] [ERROR] HTTPConnectionPool(host='balancereader', port=8080): Max retries exceeded with url: /balances/8338298020 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dedc71d0>, 'Connection to balancereader timed out. (connect timeout=3)'))
[2020-04-15 15:08:42 +0000] [9] [ERROR] HTTPConnectionPool(host='ledgerwriter', port=8080): Max retries exceeded with url: /transactions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20deead3d0>, 'Connection to ledgerwriter timed out. (connect timeout=3)'))
[2020-04-15 15:08:42 +0000] [9] [ERROR] HTTPConnectionPool(host='ledgerwriter', port=8080): Max retries exceeded with url: /transactions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f20dee7c150>, 'Connection to ledgerwriter timed out. (connect timeout=3)'))
[2020-04-15 15:08:45 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:08:45 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-15 15:08:50 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-15 15:08:52 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-15 15:08:54 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:08:56 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-15 15:08:58 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2020-04-15 15:08:59 +0000] [9] [ERROR] 404 Client Error: NOT FOUND for url: http://userservice:8080/login?username=b400e03a-7528-4ae1-9387-503593a26431&password=password
[2020-04-15 15:14:49 +0000] [9] [ERROR] Exception on /payment [POST]
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vmagent/app/flask_server.py", line 139, in payment
    _submit_transaction(transaction_data)
  File "/home/vmagent/app/flask_server.py", line 212, in _submit_transaction
    raise UserWarning(resp.json().get('msg', ''))
  File "/env/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ahmetb** [comment]
Meanwhile userservice receives no request apparently:

```
[2020-04-15 15:07:40 +0000] [6] [INFO] Starting gunicorn 20.0.4
[2020-04-15 15:07:40 +0000] [6] [INFO] Listening at: http://0.0.0.0:8080 (6)
[2020-04-15 15:07:40 +0000] [6] [INFO] Using worker: threads
[2020-04-15 15:07:40 +0000] [9] [INFO] Booting worker with pid: 9
```

**Comment by Daniel-Sanche** [comment]
I can't reproduce this, and neither can our CI system. Are you using a fresh GKE cluster? Do you have any Istio settings enabled that could be interfering with requests? Are you able to give me access to the cluster to look into it?

**Comment by askmeegs** [comment]
@ahmetb are you continuing to see this issue?
