### ISSUE TITLE
loadgenerator is crash-looping in v0.6.1

### ISSUE THREAD

**Issue by zosocanuck** [GoogleCloudPlatform/bank-of-anthos#1744]
### Describe the bug 
I'm trying to deploy bank-of-anthos v0.6.1 in docker-desktop kubernetes v1.27.2 and the loadgenerator pod is failing with error `OSError: [Errno 30] Read-only file system: '/proc/8/stat'`

### To Reproduce 
1. Set ENABLE_TRACING and ENABLE_METRICS in all deployment manifests to "false"
2. Run
```
kubectl apply -f ./extras/jwt/jwt-secret.yaml
kubectl apply -f ./kubernetes-manifests
```
3. Notice loadgenerator keeps restarting:
```
NAME                                  READY   STATUS             RESTARTS        AGE
accounts-db-0                         1/1     Running            0               11m
balancereader-84649b6689-khqmt        0/1     Running            5 (38s ago)     11m
contacts-6677c5d469-kp7x7             0/1     Running            0               11m
frontend-576cb5fdcc-nwntw             1/1     Running            0               11m
ledger-db-0                           1/1     Running            0               11m
ledgerwriter-7f688544b-9gv2m          0/1     CrashLoopBackOff   5 (2m15s ago)   11m
loadgenerator-57d4cb57cc-2p58k        0/1     CrashLoopBackOff   6 (3m39s ago)   11m
transactionhistory-7b7f5f8b6f-znzgn   0/1     CrashLoopBackOff   5 (88s ago)     11m
userservice-8c5548b4c-rvxx9           1/1     Running            0               11m
```
### Logs  
```
OSError: [Errno 30] Read-only file system: '/proc/9/stat'
2023-08-23T19:36:03Z <Greenlet at 0x4004f1c0e0: <bound method Runner.monitor_cpu_and_memory of <locust.runners.LocalRunner object at 0x4004f36c90>>> failed with OSError
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                         0     0(0.00%) |      0       0       0      0 |    0.00        0.00
[2023-08-23 19:36:03,912] loadgenerator-57d4cb57cc-2p58k/CRITICAL/locust.runners: Unhandled exception in greenlet: <Greenlet at 0x4004f1c0e0: <bound method Runner.monitor_cpu_and_memory of <locust.runners.LocalRunner object at 0x4004f36c90>>>
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.11/site-packages/locust/runners.py", line 305, in monitor_cpu_and_memory
    process = psutil.Process()
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/usr/local/lib/python3.11/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/__init__.py", line 719, in create_time
    self._create_time = self._proc.create_time()
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/_pslinux.py", line 1653, in wrapper
    return fun(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/_pslinux.py", line 1863, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/_pslinux.py", line 1653, in wrapper
    return fun(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/_common.py", line 480, in wrapper
    raise raise_from(err, None)
    ^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/psutil/_common.py", line 478, in wrapper
    return fun(self)
  File "/usr/local/lib/python3.11/site-packages/psutil/_pslinux.py", line 1695, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/_common.py", line 813, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/_common.py", line 801, in cat
    with _open(fname) as f:
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psutil/_common.py", line 765, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
      ^^^^^^^^^^^^^^^^^
```
### Environment 
- OS: MacOS Ventura 13.5.1
- Docker Desktop Kubernetes v1.27.2
- Docker Desktop 4.22.0

**Comment by minherz** [comment]
@zosocanuck thank you for letting us known about this problem. I see that beside the load generator there are two other services that fail to launch. Bank Of Anthos demo application is verified to run on GKE. While it should run on Kubernetes of any flavor we do not support all possible variations.
Because of this reason we cannot address the problem with the deployment of the app to the docker-desktop Kubernetes.
If you decide to follow up on this problem, I suggest to check resource requirements that may lead to the main issue is a lack of resources that can be a possible reason for `CrashLoopBackOff` of the services.
The logs from the load generator that you shared point on a possible problems with access permissions that a process within container has to the system. I do not have a recent experience with docker-desktop but it is possible that you should be able to configure the docker-desktop to grant escalated permissions to the containers running within Kubernetes.
