### ISSUE TITLE
transactionhistory workload does not stabilize in  autopilot GKE 

### ISSUE THREAD

**Issue by tzvetkov75** [GoogleCloudPlatform/bank-of-anthos#664]
### Describe the bug 
Deploying to auto GKE, the transactionhistory workload fails. All other workloads started ok. 

The default compute engine SA has  all roles ` Logs Writer`  and `Viewer`

It seems can not report back on startup "Error when performing Stackdriver AsyncReporter health check"

Is is scopes problem ?  Still, all other workloads started ok

### To Reproduce 

Deploy to autopilot cluster 

### Logs  

```

Info
2022-03-01T17:34:33.821724677Z<init> | Scopes in use by default credentials: [https://www.googleapis.com/auth/pubsub, https://www.googleapis.com/auth/spanner.admin, https://www.googleapis.com/auth/spanner.data, https://www.googleapis.com/auth/datastore, https://www.googleapis.com/auth/sqlservice.admin, https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/devstorage.read_write, https://www.googleapis.com/auth/cloudruntimeconfig, https://www.googleapis.com/auth/trace.append, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-vision, https://www.googleapis.com/auth/bigquery]
Info
2022-03-01T17:34:35.723324624Zinitialize | Initializing ExecutorService
Warning
2022-03-01T17:34:41.817362897ZstackdriverReporter | Error when performing Stackdriver AsyncReporter health check.
Info
2022-03-01T17:34:41.817424585Zio.grpc.StatusRuntimeException: PERMISSION_DENIED: The caller does not have permission at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.29.0.jar:1.29.0] at zipkin2.reporter.stackdriver.internal.AwaitableUnaryClientCallListener.onClose(AwaitableUnaryClientCallListener.java:100) ~[zipkin-sender-stackdriver-0.17.0.jar:?] at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[grpc-core-1.29.0.jar:1.29.0] at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.29.0.jar:1.29.0] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[grpc-core-1.29.0.jar:1.29.0] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[grpc-core-1.29.0.jar:1.29.0] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[grpc-core-1.29.0.jar:1.29.0] at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[grpc-core-1.29.0.jar:1.29.0] at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.29.0.jar:1.29.0] at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.29.0.jar:1.29.0] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_275] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_275] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_275] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_275] at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_275]
Info
2022-03-01T17:34:49.713388008Zinitialize | Initializing ExecutorService 'applicationTaskExecutor'
Info
2022-03-01T17:34:50.322933984ZgetConnection | HikariPool-1 - Starting...
Info
2022-03-01T17:34:51.623288447ZgetConnection | HikariPool-1 - Start completed. 
``` 

Many thanks

Ves

**Comment by tzvetkov75** [comment]
it was permission problem

**Comment by paulwilljones** [comment]
What permissions were missing?
I'm also seeing this with balancereader and transactionhistory on GKE Autopilot. Workload Identity is working after granting `roles/monitoring.metricWriter` and `roles/cloudtrace.agent`, and I can see traces in Cloud Trace.

```sh
k logs balancereader-84c56f4457-zmpzb
{"timestamp": "2023-01-18 12:03:55", "message": "logStarting | Starting BalanceReaderApplication using Java 17.0.4.1 on balancereader-84c56f4457-zmpzb with PID 1 (/app/classes started by ? in /)", "severity": "INFO"}
...
{"timestamp": "2023-01-18 12:04:35", "message": "enabled | Enable metrics export: true", "severity": "INFO"}
{"timestamp": "2023-01-18 12:04:41", "message": "start | publishing metrics for StackdriverMeterRegistry every 1m", "severity": "INFO"}
...
{"timestamp": "2023-01-18 12:04:49", "message": "<init> | Default credentials provider for Google Compute Engine.", "severity": "INFO"}
{"timestamp": "2023-01-18 12:04:49", "message": "<init> | Scopes in use by default credentials: [https://www.googleapis.com/auth/pubsub, https://www.googleapis.com/auth/spanner.admin, https://www.googleapis.com/auth/spanner.data, https://
www.googleapis.com/auth/datastore, https://www.googleapis.com/auth/sqlservice.admin, https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/devstorage.read_write, https://www.googleapis.com/auth/cloudruntime
config, https://www.googleapis.com/auth/trace.append, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-vision, https://www.googleapis.com/auth/bigquery, https://www.googleapis.com/auth/monitoring.write
]", "severity": "INFO"}
{"timestamp": "2023-01-18 12:04:56", "message": "stackdriverReporter | Error when performing Stackdriver AsyncReporter health check.", "severity": "WARN"}
java.lang.IllegalStateException: timeout waiting for onClose. timeoutMs=5000, resultSet=false
...
```
